server:
  port: 8080
  #设置上下文访问路径
  servlet:
    context-path: /im_cl
spring:
  datasource:
    name: im_cl
    #采用阿里druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3308/im_cl
    ##url: jdbc:mysql://82.156.171.187:3306/cl
    ##driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admincl
    #监控
    filters: stat
    initial-size: 2
    max-idle: 10
    min-idle: 2
    max-active: 20
    #超时等待时间
    max-wait: 60000
    time-between-evict-runs-millis: 60000
    #最小生存空间
    min-evictable-time-millis: 30000
    #验证连接
    validation-query: select 'x'
    #检测连接是否被空闲连接回收器回收，若检测失败，则从连接池去除
    test-while-idle: true
    #借出连接时不要测试，否则影响性能
    test-on-borrow: false

  #spring mvc 视图解析器扫描
  mvc:
    view:
      prefix: WEB-INF/pages/
      suffix: .jsp
    static-path-pattern: /**

fdfs:
  so-timeout: 3000
  connect-timeout: 1500
  thumb-image:   #缩略图生成参数
    width: 150
    height: 150
  tracker-list:
    - 1.117.93.5:22122
 ## - 82.156.196.55:22122

#  pool:
#    #从池中借出的对象的最大数目（配置为-1表示不限制）
#    max-total: -1
#    #获取连接时的最大等待毫秒数(默认配置为5秒)
#    max-wait-millis: 5000
#    #每个key最大连接数
#    max-total-per-key: 50
#    #每个key对应的连接池最大空闲连接数
#    max-idle-per-key: 10
#    #每个key对应的连接池最小空闲连接数